// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzZm5mecI295aJms-zkYeUdDro0_K-5qk',
    appId: '1:327898762107:web:27e30be2885d284123cbde',
    messagingSenderId: '327898762107',
    projectId: 'nasaa-flutter-app-4bf78',
    authDomain: 'nasaa-flutter-app-4bf78.firebaseapp.com',
    storageBucket: 'nasaa-flutter-app-4bf78.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6FwJtCxpBvinEO9yALALlocdUgGzVeOA',
    appId: '1:327898762107:android:5d1ec4dcb5eec6c723cbde',
    messagingSenderId: '327898762107',
    projectId: 'nasaa-flutter-app-4bf78',
    storageBucket: 'nasaa-flutter-app-4bf78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzRtEKu-2uXZvlmVBGZV3b6DXOVzFGOxc',
    appId: '1:327898762107:ios:38d0982f892dcade23cbde',
    messagingSenderId: '327898762107',
    projectId: 'nasaa-flutter-app-4bf78',
    storageBucket: 'nasaa-flutter-app-4bf78.firebasestorage.app',
    iosBundleId: 'com.example.nasaa',
  );
}
